version: '3.8'

services:
  backend:
    image: pi-backend:latest
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - API_URL=http://localhost:8080/api
      - SWAGGER_URL=http://localhost:8080/swagger/index.html
      - CONNECTION_STRING=mongodb://pi:password@mongodb:27017
      - LISTEN_PORT=8080
      - USE_SWAGGER=true

  miner:
    image: pi-miner:latest
    depends_on:
      - mongodb
    restart: unless-stopped
    environment:
      - CONNECTION_STRING=mongodb://pi:password@mongodb:27017
      - WORKING_DIR=home
    volumes:
      - project-insight-directory/projects.json:/usr/src/app/projects.json

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodata:/data/db
      - init-script-folder/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
